services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: "3000"
      LINKS_REDIS_URL: redis://post-redis:6379/0
    depends_on:
      - post-redis
    ports:
      - "3000:3000"

  post-redis:
    image: redis:latest
    container_name: post-redis
    restart: unless-stopped
    volumes:
      - post-redis-data:/data

volumes:
  post-redis-data:
